[package]
name = "rust"
version = "0.1.0"
authors = ["Mathieu Lapointe <matlapo.dev@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
uuid = "0.8"
anyhow = "1.0"
byteorder = "1.4"
